# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AppTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for test_google_signin
  pod 'GoogleSignIn'

  # Pods for AppTest

  target 'AppTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AppTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

